apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: baseline
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./baseline
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system