apiVersion: v1
kind: Secret
metadata:
  name: velero-aws-credentials
  namespace: velero
type: Opaque
data:
  access-key: <BASE64_ENCODED_AWS_ACCESS_KEY_ID>
  secret-key: <BASE64_ENCODED_AWS_SECRET_ACCESS_KEY>