apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero
  namespace: velero
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero
  template:
    metadata:
      labels:
        app: velero
    spec:
      serviceAccountName: velero
      containers:
        - name: velero
          image: velero/velero:v1.9.2  # Use the latest version
          env:
            - name: VELERO_S3_BUCKET
              value: "<YOUR_BUCKET_NAME>"
            - name: VELERO_S3_PREFIX
              value: "velero"
            - name: VELERO_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: velero-aws-credentials
                  key: access-key
            - name: VELERO_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: velero-aws-credentials
                  key: secret-key
